### ISSUE TITLE
Требования к дизайну сайта

### ISSUE THREAD

**Issue by vnavka** [Andy-UA/TPPS#1]
"преимущественно белый и любой другой цвет цветовой гаммы"
Не однозначное требование,

"не должно быть большого объема текстовой информации"
Понятие большого объема неознозначно

"переменчивого цвета в тексте"
Выплывает с 1го, цвет должен быть такой же как и "любой другой цвет"?

"Правообладатель, наследует права авторизованного пользователя"
Правообладатель ничем не отличается от обычного авторизованного пользователя? Зачем тогда различия?

Первоначальная структура сайта имеет вертикальную структуру?

Клиентская часть ·	Internet Explorer 
Какая версия?

Требования к техническому обеспечению?
Проходило ли тестирование на машине с такими конфигурациями? "от 1 Гб" - сапо по, без контента пользователей в бд не будет больше занимать?

**Comment by Andy-UA** [comment]
>Первоначальная структура сайта имеет вертикальную структуру?
Да
>Требования к техническому обеспечению?
>Проходило ли тестирование на машине с такими конфигурациями? "от 1 Гб" - сапо по, без
>контента пользователей в бд не будет больше занимать?
Тестирование проходило, требования включают в себя потребление ресурсов, исключительно, ПО, не включая требования ОС
